# Generated by Django 4.2.30 on 2026-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('description', models.TextField()),
                ('best_for', models.TextField()),
                ('supports_salary_income', models.BooleanField(default=False)),
                ('supports_student_income', models.BooleanField(default=False)),
                ('supports_medical_expenses', models.BooleanField(default=False)),
                ('supports_donations', models.BooleanField(default=False)),
                ('supports_employment_expenses', models.BooleanField(default=False)),
                ('supports_investment_income', models.BooleanField(default=False)),
                ('supports_capital_gains', models.BooleanField(default=False)),
                ('supports_foreign_income', models.BooleanField(default=False)),
                ('supports_rental_income', models.BooleanField(default=False)),
                ('supports_freelance_income', models.BooleanField(default=False)),
                ('supports_gig_work_income', models.BooleanField(default=False)),
                ('supports_business_expenses', models.BooleanField(default=False)),
                ('supports_home_office_expenses', models.BooleanField(default=False)),
                ('supports_vehicle_expenses', models.BooleanField(default=False)),
                ('supports_expert_help', models.BooleanField(default=False)),
                ('supports_full_service', models.BooleanField(default=False)),
                ('supports_corporate_filing', models.BooleanField(default=False)),
                ('supports_nil_corporate_return', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['price'],
            },
        ),
    ]
